spring.application.name=expense-splitter

spring.datasource.url=jdbc:postgresql://ep-sparkling-tree-azq74pfr-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_2xIAEKry7wfO

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

google.client.id=866211342910-fhp7668n17655mcgtd1ghaqsegcvi300.apps.googleusercontent.com

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your_actual_gmail@gmail.com
spring.mail.password=your16charapppassword
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true